### PR TITLE
Fix KCP remediation & add machine deployment remediation test

### LINKED ISSUE #108: Remediation is failing when machine bootstrap failed
After #103 , the machine remediation process is failing if machine bootstrap failed and node did not join the cluster successfully. The reason is that we have not handled the case when ` machine.Status.NodeRef = nil` when handling `PreTerminateDeleteHook`. Working on the fix....

### PR DESCRIPTION
**Pull request by nasusoba**
* Fix machine health check for controlplane
  * fix init lock release logic
  * add handling for remediation annotation and status
  * modify machine_controller logic to handle scenarios when `machine.Status.NodeRef=nil`
* Add 2 e2e tests:
  * kcp_remediation for controlplane remediation
  * md_remediation for machine deployment remediation
* Code cleanup
   * fix TODO for `reconcileKubeConfig`

Fixed #108

### CODE REVIEW

File: controlplane/controllers/remediation.go [hunk 1]
```diff
@@ -41,7 +42,7 @@ import (
 // reconcileUnhealthyMachines tries to remediate KThreesControlPlane unhealthy machines
 // based on the process described in https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20191017-kubeadm-based-control-plane.md#remediation-using-delete-and-recreate
 // taken from the kubeadm codebase and adapted for the k3s provider.
-func (r *KThreesControlPlaneReconciler) reconcileUnhealthyMachines(ctx context.Context, controlPlane *k3s.ControlPlane) (ret ctrl.Result, retErr error) {
+func (r *KThreesControlPlaneReconciler) reconcileUnhealthyMachines(ctx context.Context, controlPlane *k3s.ControlPlane) (ret ctrl.Result, retErr error) { //nolint:gocyclo
```
Comment (mogliang) [inline controlplane/controllers/remediation.go:45]: it's ok to have nolint here only because we want to keep code structure same with kubeadmControlplane, so that it's easier for maintain.

File: pkg/locking/control_plane_init_mutex.go [hunk 2]
```diff
@@ -14,33 +14,34 @@ See the License for the specific language governing permissions and
 limitations under the License.
 */
 
+// Package locking implements locking functionality.
```
Comment (mogliang) [inline pkg/locking/control_plane_init_mutex.go:17]: This file is from kcp, and copied everywhere, e.g. k3s provider, etcdadm-bootstrap-provider, cluster-api-provider-rke2

Shall we raise an issue to CAPI, ask if it's feasible to set this as public?

**Review by mogliang — APPROVED** [review]

File: pkg/locking/control_plane_init_mutex.go (hunk 2 above)
Comment (nasusoba) [reply pkg/locking/control_plane_init_mutex.go:17]: I will raise an issue
